debug: true
apiKey: "999999999999"
# All utilized blockchain networks along with their corresponding tokens must be defined here.
chains:
  - id: 42161 # Chain ID
    name: arbitrum # Chain name
    nativeToken: "ETH" # Native token of the chain; if not provided, defaults to the token with contract address set to zero.
    rpcEndpoints: # List of RPC endpoints; multiple entries can be specified, and requests will cycle through these.
      - https://arb1.arbitrum.io/rpc
      - https://arbitrum.llamarpc.com
      - https://arb-mainnet-public.unifra.io
      - https://arbitrum.rpc.subquery.network/public
      - https://1rpc.io/arb
    tokens: # All required tokens must be configured.
      - name: ETH # Token name
        contractAddress: "0x0000000000000000000000000000000000000000" # Token contract address
        decimals: 18 # Token decimal places; must be specified.
      - name: USDT
        contractAddress: "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"
        decimals: 6
      - name: RING
        contractAddress: "0x9e523234D36973f9e38642886197D023C88e307e"
        decimals: 18
  - id: 137
    name: polygon
    nativeToken: "MATIC"
    rpcEndpoints:
      - https://polygon-rpc.com
    tokens:
      - name: MATIC
        contractAddress: "0x0000000000000000000000000000000000000000"
        decimals: 18
      - name: USDT
        contractAddress: "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"
        decimals: 6
  - id: 1
    name: ethereum
    nativeToken: "ETH"
    rpcEndpoints:
      - https://eth.llamarpc.com
      - https://rpc.ankr.com/eth
      - https://1rpc.io/eth
      - https://ethereum-rpc.publicnode.com
    tokens:
      - name: ETH
        contractAddress: "0x0000000000000000000000000000000000000000"
        decimals: 18
      - name: RING
        contractAddress: 0x9469D013805bFfB7D3DEBe5E7839237e535ec483
        decimals: 18
  - id: 534352
    name: scroll
    nativeToken: "ETH"
    rpcEndpoints:
      - https://rpc.scroll.io
      - https://scroll.drpc.org
      - https://1rpc.io/scroll
    tokens:
      - name: ETH
        contractAddress: "0x0000000000000000000000000000000000000000"
        decimals: 18
      - name: USDT
        contractAddress: 0xf55BEC9cafDbE8730f096Aa55dad6D22d44099Df
        decimals: 6

# During rebalancing, tokens from the following configuration will be selected to determine the optimal route for swaps.
sourceTokens:
  - name: ETH # Token name, must match the token name in the 'chains' section.
    chains: # On which chains this token can be used as a source token.
      - arbitrum
      - scroll
      - ethereum
  - name: USDT
    chains:
      - arbitrum
      - scroll
      - ethereum
  - name: RING
    chains:
      - arbitrum
      - ethereum

# Providers that need to be enabled.
providers:
  - type: CEX
    name: gate.io
    config:
      key: <gate_api_key>
      secret: <gate_api_secret>
  - type: DEX
    name: uniswap
  - type: Bridge
    name: helixbridge
    config: {}
  - type: Bridge
    name: darwinia-bridge
  - type: Bridge
    liquidityName: router_nitro
    config: {}
  - type: Bridge
    liquidityName: okx
    config:
      apiKey: "xxxx"
      secretKey: "xxxx"
      passphrase: "xxxxx"
      project: "xxxxx"

# Database storage settings.
db:
  type: SQLite # Database type; options include: MySQL, PostgreSQL, SQLite.
  SQLITE: # SQLite configuration.
    path: ./omni-balance.db

# Task execution intervals.
taskInterval:
  crossChain: 30m # Interval for processing cross-chain order tasks.
  getTokenPriceInUsdt: 30m # Interval for fetching token price tasks.
  bot: 2m # Interval for running bot tasks, primarily for creating orders.
  market: 2m # Interval for executing order tasks.

notice:
  type: slack
  config:
    webhook: "https://hooks.slack.com/services/xxxxx"
    channel: "#xxxxx"
  interval: "12h"